# Generated by Django 4.2.5 on 2024-09-23 12:03
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kierunek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("opis", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Miasto",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rodzaj",
            fields=[
                (
                    "nazwa",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uczelnia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("opis", models.TextField(blank=True)),
                (
                    "Miasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.miasto"
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.rodzaj"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wydzial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("opis", models.TextField(blank=True)),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.uczelnia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Przedmiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("opis", models.TextField(blank=True)),
                (
                    "kategoria",
                    models.IntegerField(
                        choices=[
                            (1, "Bazy danych"),
                            (2, "Sieci komputerowe"),
                            (3, "Algorytmika"),
                            (4, "Sztuczna Inteligencja"),
                            (5, "Gamedev"),
                            (6, "Webdev"),
                            (7, "Programowanie mobilne"),
                            (8, "Cyberbezpieczeństwo"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "kierunek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.kierunek"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpiniaUczelnia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocena", models.IntegerField()),
                ("opis", models.TextField(blank=True)),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.uczelnia"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpiniaPrzedmiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocena", models.IntegerField()),
                ("opis", models.TextField(blank=True)),
                (
                    "przedmiot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.przedmiot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpiniaKierunek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocena", models.IntegerField()),
                ("opis", models.TextField(blank=True)),
                ("edytowana", models.BooleanField(default=False, null=True)),
                (
                    "kierunek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.kierunek"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OcenaOpiniiKierunku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocena", models.IntegerField()),
                (
                    "opinia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.opiniakierunek",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kierunek",
            name="wydzial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.wydzial"
            ),
        ),
    ]
